Accounting/Accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
]

Accounting/app/urls.py
# app/urls.py

from django.urls import path
from .views import (
    BankAccountListView, BankAccountCreateView, BankAccountDetailView,
    CustomerListView, CustomerCreateView,
    ProductListView, ProductCreateView, ProductDetailView,
    InvoiceListView, InvoiceCreateView, InvoiceDetailView, InvoiceItemCreateView, InvoiceSubmitView,
    CheckListView, CheckCreateView,
    TransferenceCreateView, TransferenceListView,
    UserSignup, UserLogin
)
from .views import UserSignup, UserLogin, PortfolioList, PortfolioCreate, PortfolioDelete
from django.contrib.auth.views import LogoutView
from django.urls import path

urlpatterns = [
    path('signup/', UserSignup.as_view(), name='signup'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),

    path('', PortfolioList.as_view(), name='pfl-list'),
    path('pfl-create/', PortfolioCreate.as_view(), name='pfl-create'),
    path('pfl-delete/pk=<int:pk>', PortfolioDelete.as_view(), name='pfl-delete'),

    path('bankaccounts/', BankAccountListView.as_view(), name='bankaccount-list'),
    path('bankaccounts/<int:pk>/', BankAccountDetailView.as_view(), name='bankaccount-detail'),
    path('bankaccounts/create/', BankAccountCreateView.as_view(), name='bankaccount-create'),
    path('customers/', CustomerListView.as_view(), name='customer-list'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer-create'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('invoices/', InvoiceListView.as_view(), name='invoice-list'),
    path('invoices/create/', InvoiceCreateView.as_view(), name='invoice-create'),
    path('invoices/<int:pk>/', InvoiceDetailView.as_view(), name='invoice-detail'),
    path('invoices/submit/<int:pk>/', InvoiceSubmitView.as_view(), name='process-invoice'),
    path('invoices/items/create/<int:pk>/', InvoiceItemCreateView.as_view(), name='invoiceitem-create'),
    path('checks/', CheckListView.as_view(), name='check-list'),
    path('checks/create/', CheckCreateView.as_view(), name='check-create'),
    path('transference/', TransferenceListView.as_view(), name='transference-list'),
    path('transference/create/', TransferenceCreateView.as_view(), name='transference-create'),
]

Accounting/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import F, Sum


# Create your models here.

class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class BankAccount(models.Model):
    ACCOUNT_TYPES = (
        ('savings', 'Savings'),
        ('checking', 'Checking'),
        ('loan', 'Loan'),
        ('store', 'Store')
    )

    bank_name = models.CharField(max_length=30, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPES)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    account_number = models.PositiveIntegerField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        initial_balance = None
        if self.pk is not None:
            initial_balance = BankAccount.objects.get(pk=self.pk).balance

        super().save(*args, **kwargs)

        if self.pk is None:
            self.account_number = self.id + 1000
            super().save(update_fields=['account_number'])

        balance_change = self.balance - initial_balance if initial_balance is not None else self.balance
        AccountHistory.objects.create(
            mother_account=self,
            balance_change=balance_change,
            remaining_balance=self.balance
        )

    def __str__(self):
        return f"{self.user.username} - {self.account_type}"


class AccountHistory(models.Model):
    mother_account = models.ForeignKey(BankAccount, related_name="account_history", on_delete=models.CASCADE)
    balance_change = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_balance = models.DecimalField(max_digits=10, decimal_places=2)
    date_changed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"History of {self.mother_account} changed on {self.date_changed}"


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.pk:
            # Update existing product
            old_product = Product.objects.get(pk=self.pk)
            quantity_change = self.quantity - old_product.quantity
            if quantity_change != 0:
                ProductHistory.objects.create(
                    product=self,
                    quantity_change=quantity_change,
                    remaining_quantity=self.quantity,
                )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductHistory(models.Model):
    product = models.ForeignKey(Product, related_name="product_history", on_delete=models.CASCADE, null=True, blank=True)
    quantity_change = models.IntegerField(null=True, blank=True)
    remaining_quantity = models.IntegerField(null=True, blank=True)
    date_changed = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"History of {self.product} changed on {self.date_changed}"


class Invoice(models.Model):
    INVOICE_TYPES = (
        ('purchase', 'Purchase'),
        ('sale', 'Sale'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    invoice_type = models.CharField(max_length=10, choices=INVOICE_TYPES)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    invoice_number = models.PositiveIntegerField(unique=True, blank=True, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    remaining_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.pk is None:
            super().save(*args, **kwargs)
            self.invoice_number = self.id + 1000
            self.save(update_fields=['invoice_number'])
        super().save(*args, **kwargs)

    def update_total_amount(self):
        total = self.invoice_items.aggregate(total=Sum('amount'))['total']
        self.total_amount = total if total else 0
        self.save(update_fields=['total_amount'])

    def update_remaining_amount(self, amount):
        self.remaining_amount = amount
        self.save(update_fields=['remaining_amount'])

    def __str__(self):
        return f"{self.customer.name} - {self.invoice_type} - {self.date}"


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='invoice_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    is_submitted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.amount = self.product.price * self.quantity
        super().save(*args, **kwargs)
        self.invoice.update_total_amount()
        self.invoice.update_remaining_amount(amount=self.amount)

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"


#
#
# class InvoiceHistory(models.Model):
#     invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
#     date_created = models.DateTimeField(auto_now_add=True)
#
#     # Add more fields as needed for history tracking
#
#     def __str__(self):
#         return f"History of {self.invoice} created on {self.date_created}"


class Check(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    bank_account = models.ForeignKey(BankAccount, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return f"{self.bank_account} - {self.amount} - {self.date}"


class Transference(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    bank_account = models.ForeignKey(BankAccount, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.bank_account} - {self.amount} - {self.date}"

Accounting/app/templates/app/bankaccount_list.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bankaccounts_list.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center">Bank Accounts</h2>
  <ul class="list-group">
    {% for account in object_list %}
        <a href="{% url 'bankaccount-detail' account.pk %}" class="text-white">
          <li class="list-group-item {% if account.account_type == 'store' %}list-group-item-success{% endif %}">
            <strong>Account ID:</strong> {{ account.account_number }}<br>
            <strong>Bank Name:</strong> {{ account.bank_name }}<br>
            <strong>Account Type:</strong> {{ account.account_type|capfirst }}<br>
            <strong>Balance:</strong> ${{ account.balance }}
          </li>
        </a>
    {% endfor %}
  </ul>
  <a href="{% url 'bankaccount-create' %}" class="btn btn-primary new-account-btn mt-3">Create New Account</a>
</div>
{% endblock %}

Accounting/app/templates/app/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    <header class="bg-dark text-white p-3 mb-4">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'bankaccount-list' %}">Bank Accounts</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'customer-list' %}">Customers</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'product-list' %}">Products</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'invoice-list' %}">Invoices</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'check-list' %}">Checks</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'transference-list' %}">transference</a></li>
                </ul>
                <div class="d-flex">
                    <button class="btn btn-primary me-2" onclick="window.location.href='/'">Home</button>
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Log out</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        {% if request.user.is_authenticated %}
            <h1 class="username">{{request.user}}</h1>
        {% else %}
            <a href="{% url 'login' %}" class="btn btn-link">Login</a>
        {% endif %}
    </div>

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybVuLkfj2lriyB7f5i8XXRV9SBCOVVSA4CDEy7i3X2QxP+Xiz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0ey4Lr1qUHA3XjjfGhP2K4e8Kuhk+N4lkk+TptE3j3p6aRYw/Jwu46R8" crossorigin="anonymous"></script>
</body>
</html>

Accounting/app/templates/app/customer_form.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/customer_form.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
  <h2>Create Customer</h2>
  <form method="post">
    {% csrf_token %}
    <label for="id_name">Name: </label>
    {{ form.name }}
    <label for="id_email">Email: </label>
    {{ form.email }}
    <button type="submit">Save</button>
  </form>
</div>
{% endblock %}

Accounting/app/templates/app/home.html
{% extends "app/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <br><br><h2>MY PORTFOLIO LIST</h2><br>
    <table class="center">
        {% for pfl in user.portfolio_set.all %}
            <tr>
                <td><h3><a href="{% url 'pfl-detail' pfl.id %}">{{pfl.name}}</a><h3></td>
                <td><button class="delete" onclick="window.location.href='/pfl-delete/pk={{pfl.id}}' ">Delete</button></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Accounting/app/templates/app/invoice_form.html
{% extends 'app/base.html' %}
{% load static %}
{% load custom_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/invoice_form.css' %}">
{% endblock %}

{% block content %}
<div class="container-2 mt-5">
  <div class="form-container">
    <h2 class="text-center">Create Invoice</h2>
    <form method="post" class="mt-4">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="id_invoice_type" class="form-label">Invoice Type:</label>
        {{ form.invoice_type|add_class:"form-control" }}
      </div>
      <div class="form-group mb-3">
        <label for="id_customer" class="form-label">Customer:</label>
        {{ form.customer|add_class:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary btn-block">Save</button>
    </form>
  </div>
</div>
{% endblock %}

Accounting/app/templates/app/invoice_list.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/invoice_list.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="card">
    <div class="card-header text-center bg-primary text-white">
      <h2>Invoices</h2>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Invoice Number</th>
            <th>Customer</th>
            <th>Type</th>
            <th>Date</th>
            <th>Total Amount</th>
          </tr>
        </thead>
        <tbody>
          {% for invoice in object_list %}
          <tr>
            <td>
              {{ invoice.invoice_number }}
            </td>
            <td>{{ invoice.customer.name }}</td>
            <td>{{ invoice.invoice_type|capfirst }}</td>
            <td>{{ invoice.date }}</td>
            <td>{{ invoice.total_amount }}</td>
            <td><a href="{% url 'invoice-detail' pk=invoice.id %}" class="btn btn-primary">invoice detail</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'invoice-create' %}" class="btn btn-success mt-3">Create New Invoice</a>
    </div>
  </div>
</div>
{% endblock %}

Accounting/app/templates/app/invoiceitem_form.html
{% extends 'app/base.html' %}
{% load static %}
{% load custom_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/invoiceitem_form.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="form-container">
    <h2 class="text-center">Add Invoice Item</h2>
    <form method="post" class="mt-4">
      {% csrf_token %}
{#      <div class="form-group mb-3">#}
{#        <label for="id_invoice" class="form-label">Invoice:</label>#}
{#        {{ form.invoice|add_class:"form-control" }}#}
{#      </div>#}
      <div class="form-group mb-3">
        <label for="id_product" class="form-label">Product:</label>
        {{ form.product|add_class:"form-control" }}
      </div>
      <div class="form-group mb-3">
        <label for="id_quantity" class="form-label">Quantity:</label>
        {{ form.quantity|add_class:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary btn-block">Save</button>
    </form>
  </div>
</div>
{% endblock %}

Accounting/app/templates/app/portfolio_confirm_delete.html
{% extends 'app/base.html' %} 
{% block title %}Delete Confirmation{% endblock %}
{% block content %}
    <br><br><h2>Delete Confirmation</h2><br>
    <form class="opt" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{object}}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

Accounting/app/templates/app/product_detail.html
{% extends 'app/base.html' %}
{% load static %}


{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">{{ object.name }} - Product Details</h4>
        </div>
        <div class="card-body">
            <p><strong>Price:</strong> ${{ object.price }}</p>
            <p><strong>Quantity:</strong> {{ object.quantity }}</p>
            
            <h5 class="mt-4">Product History</h5>
            {% if product_history %}
            <table class="table table-bordered mt-3">
                <thead class="thead-light">
                    <tr>
                        <th>Quantity Change</th>
                        <th>Remaining Quantity</th>
                        <th>Date Changed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for history in product_history %}
                    <tr>
                        <td>{{ history.quantity_change }}</td>
                        <td>{{ history.remaining_quantity }}</td>
                        <td>{{ history.date_changed }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="alert alert-info mt-3" role="alert">
                No history available for this product.
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Accounting/app/templates/app/product_form.html
{% extends 'app/base.html' %}
{% load static %}
{% load custom_filters %}


{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product_form.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Create Product</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_name">Name:</label>
          {{ form.name|add_class:'form-control'}}
        </div>
        <div class="form-group">
          <label for="id_price">Price:</label>
          {{ form.price|add_class:'form-control'}}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

Accounting/app/templates/app/signin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sign in</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">    <link rel="stylesheet" type="text/css" href="{% static 'app/account-auth.css' %}">
</head>
<body class="bg-light">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary text-white text-center">
                        <h4>Log In</h4>
                    </div>
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-info">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form.as_p }}
                            </fieldset>
                            <div class="form-group text-center">
                                <button type="submit" name="signin" class="btn btn-primary">Sign in</button>
                                <a href="{% url 'signup' %}" class="btn btn-secondary ml-2">Create your Account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Accounting/app/templates/app/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/account-auth.css' %}">
</head>
<body>
    <h1>Sign Up</h1>
    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
    <form method="post">
        {% csrf_token %}
        <fieldset>
            {{form.as_table}}
        </fieldset>
        <button type="submit" name="signup">Sign Up</button>
        <button onclick="location.href = '/login'" class="nxt-pg">Login your Account</button>
    </form>
</body>
</html>

Accounting/app/templates/app/transference_form.html
{% extends 'app/base.html' %}
{% load static %}
{% load custom_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/check_form.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Create New Check</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_bank_account">Bank Account:</label>
                    {{ form.bank_account|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_customer">Customer:</label>
                    {{ form.customer|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_amount">Amount:</label>
                    {{ form.amount|add_class:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary mt-3">Save</button>
                <a href="{% url 'check-list' %}" class="btn btn-secondary mt-3">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% if form.non_field_errors %}
<div class="modal fade show" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Error</h5>
            </div>
            <div class="modal-body">
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <a href="{% url 'transference-create' %}" class="btn btn-secondary close-btn">Close</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

Accounting/app/templates/app/transference_list.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/check_list.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Transference List</h2>
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Your Transferences</h4>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Bank Account</th>
                        <th>Customer</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transference in object_list %}
                    <tr>
                        <td>{{ transference.bank_account }}</td>
                        <td>{{ transference.customer }}</td>
                        <td>${{ transference.amount }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="{% url 'transference-create' %}" class="btn btn-success mt-3">Create New transference</a>
        </div>
    </div>
</div>
{% endblock %}